#ifndef WINNYFUNCTION_NAMES_H
#define WINNYFUNCTION_NAMES_H
/*Defines names used to lable function pages
 *and to refer to these pages in code and on
 *the user interface.
 */

#define NAME_SEARCH_PRODUCT_SCREEN "Product Management / Search"
#define NAME_CREATE_PRODUCT_SCREEN "Product Management / Create New"
#define NAME_EDIT_PRODUCT_DETAILS_SCREEN "Product Management / Edit New"
#define NAME_SEARCH_CONTACT_SCREEN "Contacts Management / Search"
#define NAME_CREATE_CONTACT_SCREEN "Contacts Management /  New"
#define NAME_EDIT_CONTACT_SCREEN "Contacts Management / Edit"
#define NAME_CASH_FLOW_SCREEN "Cash and Debt Monitoring / CashFlow"
#define NAME_GOODS_RECIEVED_SCREEN "Transactions/Goods Recieved Note"
#define NAME_INVOICE_SCREEN "Transactions/Invoice Note"
#define NAME_DELIVERY_SCREEN "Transactions/Delivery Note"
#define NAME_CASH_SALE_SCREEN "Transactions/Cash Sale Reciept"

#endif